export const PRODUCTS = [
  { id: 'nike-pegasus-40',      brand: 'Nike',       name: 'Pegasus 40',          price: 1899, tag: 'Best Seller', category: 'road',  arch: 'Neutral',   terrain: 'Road',  drop: '10mm', weight: '280g', emoji: '👟', description: 'The workhorse of the Nike lineup. Responsive cushioning and a smooth ride for everyday training miles.', features: ['React foam midsole', 'Waffle outsole', 'Breathable mesh upper', 'Wider base for stability'] },
  { id: 'asics-gel-kayano-30',  brand: 'ASICS',      name: 'Gel-Kayano 30',       price: 2499, tag: 'New',         category: 'road',  arch: 'Stability', terrain: 'Road',  drop: '8mm',  weight: '310g', emoji: '👟', description: 'Built for overpronators who need long-lasting support. Maximum cushioning with dynamic stability.', features: ['FF Blast+ ECO foam', 'GEL technology', '4D guidance system', 'LITETRUSS technology'] },
  { id: 'brooks-ghost-15',      brand: 'Brooks',     name: 'Ghost 15',            price: 1399, originalPrice: 1699, tag: 'Sale', category: 'road', arch: 'Neutral', terrain: 'Road', drop: '12mm', weight: '298g', emoji: '👟', description: 'Versatile daily trainer loved by runners of all paces. Soft, smooth, and reliable.', features: ['DNA LOFT v3 foam', 'Segmented crash pad', '3D Fit Print upper'] },
  { id: 'hoka-clifton-9',       brand: 'Hoka',       name: 'Clifton 9',           price: 2299, tag: 'New',         category: 'road',  arch: 'Neutral',   terrain: 'Road',  drop: '5mm',  weight: '249g', emoji: '👟', description: "Hoka's most iconic shoe. Maximum cushion in an impressively lightweight package.", features: ['Full-compression EVA midsole', 'Early stage Meta-Rocker', 'Engineered mesh upper'] },
  { id: 'adidas-ultraboost-23', brand: 'Adidas',     name: 'Ultraboost 23',       price: 2999, tag: 'New',         category: 'road',  arch: 'Neutral',   terrain: 'Road',  drop: '10mm', weight: '312g', emoji: '👟', description: 'Premium energy return meets street-ready style.', features: ['BOOST midsole', 'Primeknit+ upper', 'Continental outsole'] },
  { id: 'saucony-ride-16',      brand: 'Saucony',    name: 'Ride 16',             price: 1699, tag: 'Sale',        category: 'road',  arch: 'Neutral',   terrain: 'Road',  drop: '8mm',  weight: '268g', emoji: '👟', description: 'The balanced daily trainer. Perfect blend of cushion and response.', features: ['PWRRUN foam', 'FORMFIT system', 'XT-900 outsole'] },
  { id: 'nb-1080v13',           brand: 'New Balance', name: 'Fresh Foam 1080v13', price: 2199, tag: 'New',         category: 'road',  arch: 'Neutral',   terrain: 'Road',  drop: '8mm',  weight: '291g', emoji: '👟', description: 'The pinnacle of long-run comfort. Fresh Foam X for an exceptionally smooth ride.', features: ['Fresh Foam X midsole', 'Hypoknit upper', 'Ultra Heel design'] },
  { id: 'on-cloudmonster-2',    brand: 'On Running', name: 'Cloudmonster 2',      price: 3199, tag: 'New',         category: 'road',  arch: 'Neutral',   terrain: 'Road',  drop: '6mm',  weight: '270g', emoji: '👟', description: 'Monstrous cushioning meets Swiss precision. Built for runners who love maximum comfort.', features: ['CloudTec Phase technology', 'Helion superfoam', 'Speed Board'] },
  { id: 'asics-gt-2000-12',     brand: 'ASICS',      name: 'GT-2000 12',          price: 1599, originalPrice: 1999, tag: 'Sale', category: 'road', arch: 'Stability', terrain: 'Road', drop: '10mm', weight: '289g', emoji: '👟', description: 'Reliable stability shoe for overpronators at a great price point.', features: ['FF Blast foam', 'GEL technology', 'LITETRUSS technology'] },
]

export const getProductById = (id) => PRODUCTS.find(p => p.id === id)